<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Store.Common\Store.Common.csproj" />
	  <ProjectReference Include="..\Store.Domain\Store.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\Common\Commands\" />
	</ItemGroup>
  
</Project>
